--- #YAML:1.0
name:               Dancer-Template-MicroTemplate
version:            0.1
abstract:           Dancer template engine for Text::MicroTemplate
author:
    - Franck Cuny <franck@lumberjaph.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Dancer:               1.13
    Test::More:           0
    Text::MicroTemplate:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
